# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0003_auto_20161222_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='msknet_censorship.Question')),
                ('min_val', models.IntegerField(default=-4)),
                ('max_val', models.IntegerField(default=4)),
                ('min_description', models.CharField(default='-4', max_length=20)),
                ('max_description', models.CharField(default='4', max_length=20)),
            ],
            bases=('msknet_censorship.question',),
        ),
    ]
