# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0004_scalequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('axis_number', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msknet_censorship.Question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
