# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0005_axisentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisEntryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='scale_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axisentryanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msknet_censorship.Answer'),
        ),
        migrations.AddField(
            model_name='axisentryanswer',
            name='x_axis_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_axis_answer', to='msknet_censorship.AxisEntry'),
        ),
        migrations.AddField(
            model_name='axisentryanswer',
            name='y_axis_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_axis_answer', to='msknet_censorship.AxisEntry'),
        ),
    ]
