# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0006_auto_20180221_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msknet_censorship.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msknet_censorship.Question')),
            ],
        ),
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['commit_time'], 'permissions': (('manage_commit', 'Can view and do other management to commits.'),)},
        ),
        migrations.AlterField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersuggest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersuggest',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
