# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0007_auto_20180301_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='msknet_censorship.Question')),
                ('unit', models.CharField(default='', max_length=10)),
            ],
            bases=('msknet_censorship.question',),
        ),
    ]
