# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0008_dropdownquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownquestion',
            name='question_ptr',
        ),
        migrations.AddField(
            model_name='question',
            name='dropdown_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='DropdownQuestion',
        ),
    ]
