# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msknet_censorship', '0009_auto_20180303_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dropdown_unit',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
